debug

diff --git a/.github/workflows/examples.yml b/.github/workflows/examples.yml
--- a/.github/workflows/examples.yml
+++ b/.github/workflows/examples.yml
@@ -76,10 +76,10 @@ jobs:
       max-parallel: 5
       matrix:
         image:
-          - onediff:cu118
+          #- onediff:cu118
           - onediff-pro:cu121
         test-suite:
-          - diffusers_examples
+          #- diffusers_examples
           - comfy
     steps:
       - name: Login to ACR with the AccessKey pair
@@ -180,9 +180,6 @@ jobs:
         run: |
           docker exec -w /app/ComfyUI -d ${{ env.CONTAINER_NAME }} sh -c "python3 /app/ComfyUI/main.py --port 8188 > /app/ComfyUI/onediff_comfyui.log 2>&1"
           sleep 30
-          docker cp ${{ env.CONTAINER_NAME }}:/app/ComfyUI/onediff_comfyui.log .
-          ls -l ./onediff_comfyui.log
-          cat ./onediff_comfyui.log && rm ./onediff_comfyui.log
       # print to check if comfy is launched successfully
       - run: docker exec ${{ env.CONTAINER_NAME }} ps aux
       - name: Test ComfyUI
@@ -190,8 +187,10 @@ jobs:
         run: |
           run_comfy_test() {
             local workflow_name="$1"
-            false || {
-              echo "test_by_ui.py fails! print the ComfyUI logs..." && docker exec ${{ env.CONTAINER_NAME }} cat /app/ComfyUI/onediff_comfyui.log
+            docker exec -w /src/onediff/tests/comfyui ${{ env.CONTAINER_NAME }} python3 test_by_ui.py --comfy_port 8188 --workflow "$workflow_name" || {
+              echo "test_by_ui.py fails! print the ComfyUI logs..."
+              docker exec ${{ env.CONTAINER_NAME }} pkill -f "python3 /app/ComfyUI/main.py"
+              docker exec ${{ env.CONTAINER_NAME }} cat /app/ComfyUI/onediff_comfyui.log
               false
             }
           }
